version: 2.1

jobs:
  run-dev:
    docker:
      - image: cimg/node:20.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: "Install npm dependencies"
          command: "npm install"
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: "Run tests"
          command: "npm test" # or another suitable command

workflows:
  say-hello-workflow:
    jobs:
      - run-dev
