version: 2.1

jobs:
  run-dev:
    docker:
      - image: cimg/node:20.7.0
    steps:
      - checkout
      - run:
          name: "Install npm dependencies"
          command: "npm install"
      - run:
          name: "Run dev"
          command: "npm run lint"

workflows:
  say-hello-workflow:
    jobs:
      - run-dev
